name: Run Modelisation Notebook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-notebook:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Remplacez par la version de Python que vous utilisez

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assurez-vous d'avoir un fichier requirements.txt

    - name: Run Jupyter Notebook
      run: |
        pip install nbconvert
        jupyter nbconvert --to notebook --execute modelisation.ipynb --output modelisation_output.ipynb
